modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
logoFile = "logo.png"
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies.${ mod_id }]] #optional
modId = "forge" #mandatory
mandatory = true
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "curios"
mandatory = true
versionRange = "[5.4.5,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "celestial_core"
mandatory = true
versionRange = "[1.5.0,)"
ordering = "AFTER"
side = "BOTH"
