@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package com.xiaoyue.celestial_artifacts;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;